spring:
  datasource:
    url: jdbc:h2:mem:escueladb
    username: root
    password: certus
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
server:
  port: 8085
